### ISSUE TITLE
Improve design of main ride list

### ISSUE THREAD

**Issue by ConnorKrammer** [AUCSC/ride#9]
The main ride list is pretty easy on the eyes, but some elements need improvement:
 - [ ] Reduce the amount of plain white
 - [ ] Make the small region and ride type indicators more visually obvious
 - [ ] Implement icons into the design
 - [ ]  Add a visual indicator so that the user knows that clicking on a ride will display its details
   - [ ] change colour of ride on hover
   - [ ] change cursor to `pointer` in CSS to indicate clickability
   - [ ] TODO: mobile solution
 - [ ] Improve the format of the expanded details view
 - [ ] Create a more obvious visual difference between offered and requested rides

**Comment by ConnorKrammer** [comment]
Reopening due to not all requirements for completion being met
